### ISSUE TITLE
UML - Abstraction

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#11]
Work to abstract  your current design into a more supportable and documentable model.

Currently you have a MOAC (Mother of All Classes) or LotC (Lord of the Classes) type model.  This does not leverage Inheritance at all, it simply requires a consumer of the class to incorporate all facets of a Vehicle Type into each class.

Since you have gone down the Type implementation, look at further reducing it down into Categories and then grouping appropriately those Models into that Category.

**Comment by oliveje** [comment]
I have turned the Vehicle and VehicleType classes abstract for inheritance and was able to establish a total of 5 different classes.

**Comment by oliveje** [comment]
I have turned the Vehicle and VehicleType classes abstract for inheritance and was able to establish a total of 5 different classes.

**Comment by oliveje** [comment]
I have turned the Vehicle and VehicleType classes abstract for inheritance and was able to establish a total of 5 different classes.
