### ISSUE TITLE
Object - Separation

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#12]
Your Vehicle Class is nothing more than a container for other objects; it has no value or purpose.

Review your implementation, as the current design has no Inheritable Value to any object.  What benefit does your Type Class give me?  What benefit does your Vehicle Class provide me?  Currently, there is no value.

**Comment by oliveje** [comment]
Reviewed code and now there is inheritance from Vehicle(root) to VehicleType (sub) and the 30 different classes of model of vehicles (sub).
