### ISSUE TITLE
Enums - Choice?

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#13]
Currently you have two different Enums for each constructed value groups.

- ColorEnum vs Vehicle.ColorEnum
- EngineTypeEnum vs Vehicle.EngineTypeEnum
- MakeEnum vs Vehicle.MakeEnum

Which one is the correct Value Type to use?  Upon implementation of a specific Class should I compare against the Root Enum or the inherited Enum?

Pick one and go with it, don't straddle the fence.

**Comment by oliveje** [comment]
Enums have been limited to one Enum java file and the others were removed in project
