### ISSUE TITLE
Class - Implementation

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#16]
None of your classes benefit from Inheritance or Abstraction.

> * Abstraction
>         * At least one (1) Abstract Class for each Make OR Type
>             > Follow Naming Convention
>         * At least one (1) "Root" class that is the source of all Class types
> 

Implement an Inheritance Model that benefits adding new Models to a Type.

Current there is no benefit to inheriting your Class Design.

**Comment by oliveje** [comment]
Added Root class Vehicle which is Abstract and VehicleType class which is also abstract
