### ISSUE TITLE
Application - Input Validation

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#18]
Received an exception from an Invalid Input

> -- Add a Vehicle --
> Enter the make: Corolla
> Enter the type: MBUSI
> Enter the model: Rank
> Enter the year: Green
> Exception in thread "main" java.util.InputMismatchException
> 	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
> 	at java.base/java.util.Scanner.next(Scanner.java:1594)
> 	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
> 	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
> 	at CIS255_Vehicle.addVehicle(CIS255_Vehicle.java:59)
> 	at CIS255_Vehicle.showMenu(CIS255_Vehicle.java:33)
> 	at CIS255_Vehicle.main(CIS255_Vehicle.java:15)
>

**Comment by oliveje** [comment]
Added code to validate data entered to what is allowed so an Argument would not be thrown
