### ISSUE TITLE
Class - Storage

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#19]
>  * Create a Storage Class for saving of all the Vehicles created
>         > Can be a index-less or key-less Object (such as a ArrayList, Vector, Stack, Queue, etc.)
>         > Should be functional, ArrayList<> will probably be the easiest but your choice on complexity.
>         > Make the name relevant to its purpose
>         > Must store the entered Vehicles as their constructed Type

**Comment by oliveje** [comment]
Added Storage class
