### ISSUE TITLE
Class - File Handler

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#20]
>     * Create a File Handler to output the Storage Class to a File
>         > File should be a simple CSV, with a Header Row
>         > Each row will be terminated with a CRLF or New-Line character
>         > File Extension: csv
>         > Delimiter Character: | (pipe symbol)

**Comment by oliveje** [comment]
Are saying that a file does not create?

**Comment by oliveje** [comment]
Issue resolved

**Comment by oliveje** [comment]
Added file handler class updated UML to reflect
